-- AlterTable
ALTER TABLE "Team" ADD COLUMN "regStatus" TEXT NOT NULL DEFAULT 'APPROVED';
ALTER TABLE "Team" ADD COLUMN "regNote" TEXT;
ALTER TABLE "Team" ADD COLUMN "regAppeal" TEXT;
ALTER TABLE "Team" ADD COLUMN "regAppealAt" TIMESTAMP(3);
